# Generated by Django 5.1.5 on 2025-02-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_userspace_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankconnection',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankconnection',
            name='currency',
        ),
        migrations.CreateModel(
            name='ConnectedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountIban', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('bankConnectionId', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bankConnection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.bankconnection', verbose_name='bank_connection')),
            ],
        ),
    ]
