# Generated by Django 5.1.5 on 2025-02-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_bankconnection_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedaccounts',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
