# Generated by Django 5.1.5 on 2025-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_rename_updated_at_connectedaccounts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccounts',
            name='accountId',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
