# Generated by Django 5.1.5 on 2025-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_connectedaccounts_accountid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedaccounts',
            name='balance',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
