# Generated by Django 5.1.5 on 2025-02-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_connectedaccounts_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedaccounts',
            name='accountId',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='connectedaccounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
