# Generated by Django 5.1.5 on 2025-03-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_connectedaccounts_accountid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttoken',
            name='refresh_token',
        ),
    ]
