# Generated by Django 5.1.5 on 2025-03-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_clienttoken_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedaccounts',
            name='bankConnection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.bankconnection', verbose_name='bank_connection'),
        ),
    ]
