# Generated by Django 4.2.1 on 2024-02-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
