# Generated by Django 5.1.5 on 2025-01-17 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MaxValueValidator(99000000000)])),
                ('collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('father_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space')),
            ],
        ),
    ]
