# Generated by Django 4.2.1 on 2025-01-06 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MaxValueValidator(99000000000)]),
        ),
    ]
