# Generated by Django 4.2.1 on 2024-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='collected',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
