# Generated by Django 4.2.1 on 2024-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_alter_goal_collected_alter_goal_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
