# Generated by Django 4.2 on 2023-09-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='minus',
            new_name='spent',
        ),
    ]
