# Generated by Django 4.2.1 on 2025-01-04 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MaxValueValidator(99000000000)]),
        ),
    ]
