# Generated by Django 4.2 on 2023-08-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_remove_space_total_balance'),
        ('total_balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbalance',
            name='father_space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space'),
        ),
    ]
