# Generated by Django 4.2.1 on 2024-11-21 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('importance', models.CharField(choices=[('important', 'Important'), ('medium', 'Medium'), ('standard', 'Standard')], max_length=25)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.ManyToManyField(related_name='viewed_notification_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('importance', models.CharField(choices=[('important', 'Important'), ('medium', 'Medium'), ('standard', 'Standard')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.ManyToManyField(related_name='viewed_notification', to=settings.AUTH_USER_MODEL)),
                ('who_can_view', models.ManyToManyField(related_name='who_can_view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
