# Generated by Django 4.2.1 on 2025-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('country', models.CharField(choices=[('germany', 'Germany'), ('czechia', 'Czechia'), ('usa', 'USA'), ('ukraine', 'Ukraine')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
