# Generated by Django 4.2.1 on 2023-09-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0002_remove_space_total_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=4)),
                ('father_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space')),
            ],
        ),
    ]
