# Generated by Django 4.2.1 on 2025-02-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('father_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space')),
            ],
        ),
    ]
