# Generated by Django 4.2.1 on 2024-04-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('total_balance', '0002_alter_totalbalance_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalbalance',
            name='currency',
        ),
    ]
