# Generated by Django 4.2.1 on 2024-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
