# Generated by Django 4.2.1 on 2024-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
