# Generated by Django 4.2.1 on 2024-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0003_alter_cryptocurrency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
