# Generated by Django 4.2.1 on 2024-04-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0004_alter_cryptocurrency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='code',
        ),
    ]
