# Generated by Django 4.2.1 on 2024-04-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0004_alter_cryptocurrency_price_eur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cryptocurrency',
            new_name='Сryptocurrency',
        ),
    ]
