# Generated by Django 4.2.1 on 2024-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
