# Generated by Django 4.2.1 on 2024-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_stocks', '0002_remove_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
