# Generated by Django 4.2.1 on 2023-12-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_remove_space_owner_memberpermissions_space_members'),
        ('messenger', '0004_alter_spacegroup_father_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacegroup',
            name='father_space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space.space'),
        ),
    ]
