# Generated by Django 4.2.1 on 2024-05-01 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0005_alter_spacegroup_father_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessangerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_text', models.CharField(choices=[('nobody', 'Nobody'), ('people_in_space', 'People in space'), ('everybody', 'Everybody')], default='everybody', max_length=20)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
