# Generated by Django 4.2.1 on 2024-05-04 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0006_messangersettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessangerSettings',
            new_name='MessengerSettings',
        ),
    ]
