# Generated by Django 4.2.1 on 2024-05-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_rename_messangersettings_messengersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessengerSettings',
        ),
    ]
