# Generated by Django 4.2.1 on 2024-03-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0002_alter_cryptocurrency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
