# Generated by Django 4.2.1 on 2024-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0003_alter_cryptocurrency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
