names_of_companies = {
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "AMZN": "Amazon",
    "GOOGL": "Google",
    "ORCL": "Oracle",
    "TSLA": "Tesla",
    "BABA": "Alibaba",
    "JNJ": "Johnson & Jonson",
    "BAC": "Bank of America",
    "XOM": "Exxon Mobil",
    "GE": "General Electric",
    "KO": "Cola-Cola",
    "PG": "Procter & Gamble",
    "V": "Visa",
    "MA": "Mastercard",
    "JPM": "JPMorgan",
    "PFE": "Pfizer",
    "INTC": "Intel",
    "CSCO": "Cisco Systems",
    "DIS": "Walt Disney",
    "IBM": "IBM Corporation",
    "BA": "Boeing",
    "NFLX": "Netflix",
    "JCI": "Johnson Controls",
    "GM": "General Motors",
    "CVX": "Chevron",
    "PEP": "PepsiCo",
    "GS": "Goldman Sachs",
    "MMM": "3M",
    "HON": "Honeywell"
    }
