# Generated by Django 4.2.1 on 2024-04-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyexpense',
            old_name='periodic',
            new_name='periodic_expense',
        ),
    ]
