# Generated by Django 4.2.1 on 2024-11-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tink', '0002_remove_tinkaccount_space_remove_tinkuser_user_and_more'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyexpense',
            name='tink_account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tink.tinkaccount', verbose_name='tink_account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyexpense',
            name='tink_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historyincome',
            name='tink_account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tink.tinkaccount', verbose_name='tink_account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyincome',
            name='tink_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyexpense',
            name='from_acc',
            field=models.JSONField(blank=True, null=True, verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='historyincome',
            name='account',
            field=models.JSONField(blank=True, null=True, verbose_name='account'),
        ),
    ]
