# Generated by Django 4.2.1 on 2025-03-11 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_clienttoken_refresh_token_and_more'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyexpense',
            name='tink_account',
        ),
        migrations.RemoveField(
            model_name='historyexpense',
            name='tink_id',
        ),
        migrations.RemoveField(
            model_name='historyincome',
            name='tink_account',
        ),
        migrations.RemoveField(
            model_name='historyincome',
            name='tink_id',
        ),
        migrations.AddField(
            model_name='historyexpense',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cards.connectedaccounts', verbose_name='bank_account'),
        ),
        migrations.AddField(
            model_name='historyexpense',
            name='transaction_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historyincome',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cards.connectedaccounts', verbose_name='bank_account'),
        ),
        migrations.AddField(
            model_name='historyincome',
            name='transaction_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
