# Generated by Django 4.2.1 on 2023-09-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyincome',
            old_name='acc',
            new_name='account',
        ),
    ]
