# Generated by Django 5.1.5 on 2025-03-07 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_clienttoken_refresh_token'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyexpense',
            name='tink_account',
        ),
        migrations.RemoveField(
            model_name='historyexpense',
            name='tink_id',
        ),
        migrations.RemoveField(
            model_name='historyincome',
            name='tink_account',
        ),
        migrations.RemoveField(
            model_name='historyincome',
            name='tink_id',
        ),
        migrations.AddField(
            model_name='historyexpense',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cards.connectedaccounts', verbose_name='bank_account'),
        ),
        migrations.AddField(
            model_name='historyexpense',
            name='transaction_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historyincome',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cards.connectedaccounts', verbose_name='bank_account'),
        ),
        migrations.AddField(
            model_name='historyincome',
            name='transaction_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
