# Generated by Django 4.2.1 on 2024-06-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_category_order'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyexpense',
            name='to_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='category.category', verbose_name='to_cat'),
        ),
    ]
