# Generated by Django 4.2.1 on 2024-06-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_alter_goal_collected_alter_goal_goal'),
        ('category', '0006_remove_category_order'),
        ('account', '0002_alter_account_balance'),
        ('history', '0002_alter_historyexpense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyexpense',
            name='from_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account', verbose_name='from_acc'),
        ),
        migrations.AlterField(
            model_name='historyexpense',
            name='to_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.category', verbose_name='to_cat'),
        ),
        migrations.AlterField(
            model_name='historyincome',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='from_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_from', to='account.account', verbose_name='from_acc'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='from_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_from_goal', to='goal.goal', verbose_name='from_goal'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='to_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_to', to='account.account', verbose_name='to_acc'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='to_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_to_goal', to='goal.goal', verbose_name='to_goal'),
        ),
    ]
