# Generated by Django 5.1.5 on 2025-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_historyexpense_tink_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyexpense',
            name='bank_account',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historyincome',
            name='bank_account',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
