# Generated by Django 4.2.1 on 2024-11-23 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tink', '0002_remove_tinkaccount_space_remove_tinkuser_user_and_more'),
        ('history', '0002_historyexpense_tink_account_historyexpense_tink_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyexpense',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='historyexpense',
            name='new_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historyexpense',
            name='tink_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tink.tinkaccount', verbose_name='tink_account'),
        ),
        migrations.AlterField(
            model_name='historyincome',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='historyincome',
            name='new_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
