# Generated by Django 4.2.1 on 2024-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_historyexpense_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyincome',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
