# Generated by Django 4.2.1 on 2024-11-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tink', '0002_remove_tinkaccount_space_remove_tinkuser_user_and_more'),
        ('history', '0003_alter_historyexpense_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyincome',
            name='tink_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tink.tinkaccount', verbose_name='tink_account'),
        ),
    ]
