# Generated by Django 4.2.1 on 2024-11-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_historyincome_tink_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyexpense',
            name='tink_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historyincome',
            name='tink_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
