# Generated by Django 4.2.1 on 2024-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_historyincome_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyincome',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
