# Generated by Django 4.2.1 on 2024-03-03 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_historyincome_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyincome',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
