# Generated by Django 4.2.1 on 2024-12-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tink', '0002_remove_tinkaccount_space_remove_tinkuser_user_and_more'),
        ('history', '0005_alter_historyexpense_tink_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyincome',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historyincome',
            name='tink_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tink.tinkaccount', verbose_name='tink_account'),
        ),
    ]
