# Generated by Django 4.2.1 on 2024-03-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_alter_historyincome_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyexpense',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historyexpense',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
