# Generated by Django 4.2.1 on 2024-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_alter_historyexpense_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyexpense',
            name='periodic',
            field=models.BooleanField(default=False),
        ),
    ]
