# Generated by Django 4.2.1 on 2024-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_historytransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyexpense',
            name='amount_in_default_currency',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyincome',
            name='amount_in_default_currency',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historytransfer',
            name='amount_in_default_currency',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historyexpense',
            name='to_cat',
            field=models.CharField(blank=True, default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historyincome',
            name='comment',
            field=models.CharField(blank=True, default=1, max_length=300),
            preserve_default=False,
        ),
    ]
