# Generated by Django 4.2.1 on 2024-03-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_historyexpense_amount_in_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytransfer',
            name='goal_is_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
