# Generated by Django 4.2.1 on 2024-03-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_historytransfer_goal_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytransfer',
            name='collected',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historytransfer',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
