# Generated by Django 4.2.1 on 2024-04-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_historytransfer_collected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyexpense',
            old_name='periodic',
            new_name='periodic_expense',
        ),
    ]
