# Generated by Django 5.1.5 on 2025-01-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='father_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space'),
        ),
    ]
