# Generated by Django 4.2.1 on 2025-01-08 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MaxValueValidator(99000000000)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='spent',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MaxValueValidator(99000000000)]),
        ),
    ]
