# Generated by Django 4.2.1 on 2024-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='spent',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
