# Generated by Django 4.2.1 on 2024-06-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_limit_alter_category_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
