# Generated by Django 4.2.1 on 2024-10-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
