# Generated by Django 4.2.1 on 2024-04-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinkuser',
            name='external_user_tink_id',
        ),
    ]
