# Generated by Django 4.2.1 on 2024-11-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
        ('tink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinkaccount',
            name='space',
        ),
        migrations.RemoveField(
            model_name='tinkuser',
            name='user',
        ),
        migrations.AddField(
            model_name='tinkaccount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tink_accounts', to='tink.tinkuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tinkuser',
            name='space',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='space.space'),
            preserve_default=False,
        ),
    ]
