# Generated by Django 4.2.1 on 2023-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_alter_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verify_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verify_email',
            field=models.BooleanField(default=False),
        ),
    ]
