# Generated by Django 4.2.1 on 2025-01-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
