# Generated by Django 4.2.1 on 2025-01-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_space_members_slots'),
        ('store', '0003_subscription_stripe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='space_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='father_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space'),
        ),
    ]
