# Generated by Django 4.2.1 on 2025-01-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_space_members_slots'),
        ('store', '0004_remove_paymenthistory_space_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='father_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_user',
            field=models.CharField(max_length=255),
        ),
    ]
