# Generated by Django 4.2 on 2023-08-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='total_balance',
        ),
    ]
