# Generated by Django 4.2.1 on 2024-07-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts', models.JSONField(verbose_name='state of accounts')),
                ('categories', models.JSONField(verbose_name='state of categories')),
                ('total_balance', models.JSONField(verbose_name='state of total balance')),
                ('date', models.DateField(verbose_name='date of backup')),
                ('father_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space')),
            ],
        ),
    ]
