# Generated by Django 5.1.5 on 2025-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
