# Generated by Django 4.2.1 on 2024-01-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_remove_space_owner_memberpermissions_space_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberpermissions',
            old_name='add_users',
            new_name='add_members',
        ),
        migrations.RenameField(
            model_name='memberpermissions',
            old_name='edit_users',
            new_name='edit_members',
        ),
        migrations.RenameField(
            model_name='memberpermissions',
            old_name='remove_users',
            new_name='remove_members',
        ),
        migrations.AddField(
            model_name='memberpermissions',
            name='income',
            field=models.BooleanField(default=True, verbose_name='can income'),
        ),
    ]
