FROM nginx:latest

# Устанавливаем wget
RUN apt-get update && apt-get install -y wget

# Удаляем стандартную конфигурацию nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копируем наш основной конфиг nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Копируем наш серверный конфиг
COPY default.conf /etc/nginx/conf.d/default.conf

# Открываем порты
EXPOSE 80 443
