# Generated by Django 4.2 on 2023-09-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='time_update',
        ),
    ]
