# Generated by Django 4.2 on 2023-08-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('comment', models.CharField(max_length=300)),
                ('from_acc', models.CharField(max_length=24)),
                ('to_cat', models.CharField(max_length=24, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('father_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='father_space')),
            ],
        ),
    ]
