# Generated by Django 5.1.5 on 2025-01-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='text',
            field=models.CharField(max_length=800),
        ),
    ]
