# Generated by Django 4.2.1 on 2025-02-17 18:58

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('CZECH', 'Čeština'), ('CHINESE', '中国'), ('ARABIC', 'العربية'), ('RUSSIAN', 'Русский'), ('JAPANESE', '日本語'), ('UKRAINIAN', 'Українська'), ('GERMAN', 'Deutsch'), ('FRENCH', 'Française')], default='ENGLISH', max_length=20)),
                ('tag', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('free', 'Free'), ('business_plan', 'Business plan'), ('business_member_lic', 'Business member license'), ('business_member_plan', 'Business member plan'), ('business_lic', 'Business license'), ('sponsor', 'Sponsor'), ('employee', 'Employee')], max_length=20), blank=True, default=['free'], size=None)),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('new_password', models.CharField(blank=True, max_length=24, null=True)),
                ('verify_code', models.CharField(blank=True, max_length=12, null=True)),
                ('code_from_new_email', models.CharField(blank=True, max_length=12, null=True)),
                ('password_reset_code', models.CharField(blank=True, max_length=12, null=True)),
                ('verify_new_password', models.CharField(blank=True, max_length=12, null=True)),
                ('groups', models.ManyToManyField(related_name='custom_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
