# Generated by Django 4.2.1 on 2024-08-07 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('sponsor', 'Sponsor'), ('employee', 'Employee')], max_length=12), blank=True, default=['premium'], size=None),
        ),
    ]
