# Generated by Django 4.2.1 on 2024-11-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verify_new_password',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
