# Generated by Django 4.2.1 on 2025-02-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('business_plan', 'Business plan'), ('business_member_lic', 'Business member license'), ('business_member_plan', 'Business member plan'), ('business_lic', 'Business license'), ('sponsor', 'Sponsor'), ('employee', 'Employee')], default=['free'], max_length=20),
        ),
    ]
