# Generated by Django 4.2.1 on 2025-01-07 05:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('sponsor', 'Sponsor'), ('employee', 'Employee'), ('business', 'Business')], max_length=12), blank=True, default=['premium'], size=None),
        ),
    ]
