# Generated by Django 5.1.5 on 2025-02-03 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('free', 'Free'), ('business_plan', 'Business plan'), ('business_member_lic', 'Business member license'), ('business_member_plan', 'Business member plan'), ('business_lic', 'Business license'), ('sponsor', 'Sponsor'), ('employee', 'Employee')], max_length=20), blank=True, default=['free'], size=None),
        ),
    ]
