# Generated by Django 4.2.1 on 2025-02-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_customuser_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
