# Generated by Django 4.2.1 on 2024-09-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_alter_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_password',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
