# Generated by Django 4.2.1 on 2024-12-15 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_alter_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('free', 'Free'), ('business_plan', 'Business plan'), ('business_lic', 'Business license'), ('sponsor', 'Sponsor'), ('employee', 'Employee'), ('premium/pre', 'Premium/Pre'), ('standard/pre', 'Standard/Pre')], max_length=15), blank=True, default=['free'], size=None),
        ),
    ]
