# Generated by Django 4.2.1 on 2023-10-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_customuser_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('SPANISH', 'Español'), ('CHINESE', '中国'), ('ARABIC', 'العربية'), ('RUSSIAN', 'Русский'), ('JAPANESE', '日本語'), ('UKRAINIAN', 'Українська'), ('GERMAN', 'Deutsch'), ('FRENCH', 'Française')], default='ENGLISH', max_length=20),
        ),
    ]
