# Generated by Django 4.2.1 on 2024-09-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_customuser_new_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
