# Generated by Django 4.2.1 on 2024-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_alter_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verify_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verify_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
