# Generated by Django 4.2.1 on 2025-01-09 17:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_alter_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('free', 'Free'), ('business_plan', 'Business plan'), ('business_member', 'Business member'), ('business_lic', 'Business license'), ('sponsor', 'Sponsor'), ('employee', 'Employee')], max_length=20), blank=True, default=['free'], size=None),
        ),
    ]
