# Generated by Django 4.2.1 on 2024-04-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_remove_customuser_verify_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='currency',
        ),
    ]
