# Generated by Django 4.2.1 on 2024-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0008_remove_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
