# Generated by Django 4.2.1 on 2024-04-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0009_customuser_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_from_new_email',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
