# Generated by Django 4.2.1 on 2023-12-02 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0002_remove_space_total_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='owner',
        ),
        migrations.CreateModel(
            name='MemberPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('delete_categories', models.BooleanField(default=True, verbose_name='can delete categories')),
                ('edit_categories', models.BooleanField(default=True, verbose_name='can edit categories')),
                ('create_categories', models.BooleanField(default=True, verbose_name='can create categories')),
                ('delete_goals', models.BooleanField(default=True, verbose_name='can delete goals')),
                ('edit_goals', models.BooleanField(default=True, verbose_name='can edit goals')),
                ('create_goals', models.BooleanField(default=True, verbose_name='can create goals')),
                ('delete_accounts', models.BooleanField(default=True, verbose_name='can delete accounts')),
                ('edit_accounts', models.BooleanField(default=True, verbose_name='can edit accounts')),
                ('create_accounts', models.BooleanField(default=True, verbose_name='can create accounts')),
                ('remove_users', models.BooleanField(default=True, verbose_name='can remove users from space')),
                ('edit_users', models.BooleanField(default=True, verbose_name="can edit users' permissions in space")),
                ('add_users', models.BooleanField(default=True, verbose_name='can add users to space')),
                ('create_recurring_spends', models.BooleanField(default=True, verbose_name='can create recurring spends')),
                ('edit_recurring_spends', models.BooleanField(default=True, verbose_name='can edit recurring spends')),
                ('delete_recurring_spends', models.BooleanField(default=True, verbose_name='can delete recurring spends')),
                ('edit_history', models.BooleanField(default=True, verbose_name='can edit history records')),
                ('delete_history', models.BooleanField(default=True, verbose_name='can delete history records')),
                ('add_bank_accounts', models.BooleanField(default=True, verbose_name='can add bank accounts to space')),
                ('remove_bank_accounts', models.BooleanField(default=True, verbose_name='can remove bank accounts from space')),
                ('spend', models.BooleanField(default=True, verbose_name='can spends')),
                ('transfer', models.BooleanField(default=True, verbose_name='can transfers')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='member')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space', verbose_name='space')),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(through='space.MemberPermissions', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
