# Generated by Django 4.2.1 on 2023-12-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_remove_space_owner_memberpermissions_space_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpermissions',
            name='income',
            field=models.BooleanField(default=True, verbose_name='can income'),
        ),
    ]
