# Generated by Django 4.2.1 on 2024-12-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.IntegerField()),
                ('assets', models.CharField(max_length=50, verbose_name='Тип активу')),
                ('data', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Дані')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
        ),
    ]
