# Generated by Django 4.2.1 on 2024-12-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='projectoverview',
            name='assets',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='data',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
