# Generated by Django 5.1.5 on 2025-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoverview',
            name='data',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
