# Generated by Django 4.2.1 on 2024-12-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_projectoverview_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoverview',
            name='updated_date',
            field=models.DateField(),
        ),
    ]
