# Generated by Django 4.2 on 2023-08-24 07:15

from django.db import migrations, models
import requests


def fill_currencies(apps, schema_editor):
    Currency = apps.get_model('converter', 'Currency')
    url = str.__add__('http://data.fixer.io/api/latest?access_key=', "65268712d3852ba0ad7d085115ac7118")
    data = requests.get(url).json()
    rates = data["rates"]

    result = []

    with open("P:\My_Projects\SpendSpl\\apps\converter\currencies.txt", "r") as file:
        for i in file.readlines()[2:]:
            for j in [(i[2:-13].strip() + " - " + i[36:].strip()[:-1].strip()).split(' - ')]:
                result.append(j + [rates[j[1]]])

    for i in sorted(result, key=lambda x: x[0]):
        Currency.objects.create(currency=i[0], iso_code=i[1], euro=i[2])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=30)),
                ('iso_code', models.CharField(max_length=3)),
                ('euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(fill_currencies),
    ]
